kk="tt"
exp_name="baseline_1"

checkpoint="The model you trained"
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 3 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 0 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 1 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 2 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 0 2 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 0 1 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 1 3 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 1 2 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 2 3 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 0 3 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 0 1 2 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 1 2 3 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 0 2 3 --checkpoint ${checkpoint} --exp_name tt
CUDA_VISIBLE_DEVICES=1 python3 test_18_smu.py  --modal_list 0 1 3 --checkpoint ${checkpoint} --exp_name tt